//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RegistrationOfStudents
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transkript
    {
        public int TranskriptID { get; set; }
        public string Fenn { get; set; }
        public string Semestr { get; set; }
        public string Kredit { get; set; }
        public string Qiymet { get; set; }
        public int Bal { get; set; }
    
        public virtual Students Student { get; set; }
    }
}
